# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  paths:
    include:
      - result/*

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

pool:
  name: local agent pool

stages:
- stage: BuildAndPush
  displayName: Build and push image
  jobs:
  - job: BuildAndPush
    displayName: Build and push
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'DockerHub'
        repository: 'rathivishal52/resultapp'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
